import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
from fpdf import FPDF
import base64

# 1. Dashboard Config
st.set_page_config(page_title="AI Stock Terminal Pro", layout="wide")

# 2. Sidebar - Dropdown and PDF Generator
st.sidebar.header("Terminal Settings")
ticker_dict = {
    "Apple (AAPL)": "AAPL",
    "Tesla (TSLA)": "TSLA",
    "NVIDIA (NVDA)": "NVDA",
    "Microsoft (MSFT)": "MSFT",
    "Bitcoin (BTC-USD)": "BTC-USD"
}
selected_display = st.sidebar.selectbox("Select Asset", list(ticker_dict.keys()))
selected_ticker = ticker_dict[selected_display]

# 3. Data Engine
@st.cache_data
def get_live_data(ticker):
    data = yf.download(ticker, period="2y")
    if data.empty: return None
    # Calculate RSI
    delta = data['Close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    rs = gain / loss
    data['RSI'] = 100 - (100 / (1 + rs))
    return data.dropna()

# 4. News Feed Function
def get_stock_news(ticker):
    stock = yf.Ticker(ticker)
    return stock.news[:5]

# 5. PDF Generation Logic
def create_pdf(ticker, price, prediction):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt=f"AI Stock Analysis Report: {ticker}", ln=True, align='C')
    pdf.set_font("Arial", size=12)
    pdf.ln(10)
    pdf.cell(200, 10, txt=f"Current Price: ${price:.2f}", ln=True)
    pdf.cell(200, 10, txt=f"AI Predicted Next Close: ${prediction:.2f}", ln=True)
    pdf.ln(10)
    pdf.cell(200, 10, txt="Generated by Bakari's AI Engine", ln=True)
    return pdf.output(dest='S').encode('latin-1')

# 6. Main Dashboard
st.title(f"📊 {selected_display} Intelligence Dashboard")
df = get_live_data(selected_ticker)

if df is not None:
    # Load Model
    model = load_model("stock_model.h5", compile=False)
    current_price = float(df['Close'].iloc[-1])
    
    # Prediction (Example logic - ensure this matches your training)
    prediction = current_price * 1.002 # Placeholder for demo; use model.predict here
    
    # Metrics
    m1, m2, m3 = st.columns(3)
    m1.metric("Current Price", f"${current_price:.2f}")
    m2.metric("AI Prediction", f"${prediction:.2f}", delta=f"{prediction-current_price:.2f}")
    m3.metric("RSI (Momentum)", f"{df['RSI'].iloc[-1]:.2f}")

    # News Section
    st.divider()
    st.subheader(f"📰 Latest {selected_ticker} Headlines")
    for news in get_stock_news(selected_ticker):
        with st.expander(news['title']):
            st.write(f"Publisher: {news['publisher']}")
            st.write(f"[Link to Article]({news['link']})")

    # Download Section
    pdf_data = create_pdf(selected_ticker, current_price, prediction)
    st.sidebar.download_button(
        label="📥 Download PDF Report",
        data=pdf_data,
        file_name=f"{selected_ticker}_report.pdf",
        mime="application/pdf"
    )